Parameters:
  SourceStackName:
    Description: "Source stack name"
    Type: String
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: "myVpcSTACK"
Resources:  
  mySUBNET:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${SourceStackName}-VpcID" 
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: "Name"
          Value: "mySUBNET"